### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by bartekrutkowski** [appscode/phabricator-go#4]
I was wondering wether this code is usable as a library to make connections to one's own Phabricator instance? Given there's no documentation on this code, I have to guess from the lecture of it, and it seems like it requires a `github.com/appscode/client/cli` package, which in turn has hardcoded values for endpoint API IP's, so it seems like despite the code being publicly available, it isn't in fact usable for other people Phabricator instances?
Thanks in advance for any clarification!

**Comment by tamalsaha** [comment]
Thanks for your interest. We wrote this for our particular installation. It works as-is for us and don't have plans to further extend it unless something breaks. If you would like to make it work for any Phabricator installation and/or add support for additional apis, we are happy to review prs for that.
